name: Frontend CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ThreeTierAppProductAPI/ProductApp-UI-main


      - name: Build Frontend
        run: npm run build
        working-directory: ThreeTierAppProductAPI/ProductApp-UI-main
